# CONSOLIDATED CLUSTER TERRAFORM - PROPER MODULE STRUCTURE
# Single terraform managing all cluster layers with proper dependencies

# PROVIDER CONFIGURATIONS
# Bootstrap providers are available immediately, SSO providers require services to be deployed first
# Provider versions are centrally defined in terraform.tf

# Proxmox provider using credentials from pve-auth module
provider "proxmox" {
  endpoint = "https://${var.proxmox_api_host}:8006/"
  username = "terraform@pve"
  # Parse the token from the JSON config returned by pve-auth module
  api_token = jsondecode(jsondecode(module.pve_auth.terraform_token)["config_json"])["token"]
  insecure  = true # Dev environment with self-signed certs
}

# PowerDNS provider - will be available after infrastructure deployment
provider "powerdns" {
  server_url = "http://10.0.3.3:8081" # PowerDNS API endpoint on cluster VIP
  # API key will be set via TF_VAR_powerdns_api_key environment variable
  api_key = var.powerdns_api_key
}

# Authentik provider - will be available after infrastructure + SSO deployment
provider "authentik" {
  url = "https://authentik.${var.cluster_domain}"
  # Token will be set via TF_VAR_authentik_token environment variable or generated by bootstrap
  token = var.authentik_token
}

# Harbor provider - will be available after infrastructure + SSO deployment
provider "harbor" {
  url      = "https://harbor.${var.cluster_domain}"
  username = "admin"
  # Password will be set via TF_VAR_harbor_admin_password environment variable
  password = var.harbor_admin_password
}

# Gitea provider - will be available after infrastructure + SSO deployment
provider "gitea" {
  base_url = "https://gitea.${var.cluster_domain}"
  # Token will be set via TF_VAR_gitea_admin_token environment variable
  token = var.gitea_admin_token
}

# PVE-AUTH MODULE: Creates Proxmox users and API tokens
module "pve_auth" {
  source = "./modules/pve-auth"

  proxmox_host     = var.proxmox_host
  proxmox_api_host = var.proxmox_api_host
}

# INFRASTRUCTURE MODULE: Creates Talos cluster, CNI, and Flux GitOps
module "infrastructure" {
  source     = "./modules/infrastructure"
  depends_on = [module.pve_auth]

  proxmox_node_name = var.proxmox_node_name

  # Cluster configuration
  cluster_name       = var.cluster_name
  cluster_vip        = var.cluster_vip
  cluster_networks   = var.cluster_networks
  controller_count   = var.controller_count
  worker_count       = var.worker_count
  prefix             = var.prefix
  vm_id_ranges       = var.vm_id_ranges
  talos_version      = var.talos_version
  kubernetes_version = var.kubernetes_version

  # Headscale/Tailscale integration
  headscale_user         = var.headscale_user
  headscale_login_server = var.headscale_login_server

}

# STORAGE MODULE: Generates CSI secrets for persistent storage
module "storage" {
  source     = "./modules/storage"
  depends_on = [module.infrastructure]

  csi_config = module.pve_auth.csi_config
}

# GITOPS MODULE: SSO services (Authentik, Vault, Harbor, Gitea, Matrix)
module "gitops" {
  source     = "./modules/gitops"
  depends_on = [module.infrastructure]

  cluster_domain = var.cluster_domain
}

# DNS MODULE: PowerDNS zone and record management
module "dns" {
  source     = "./modules/dns"
  depends_on = [module.infrastructure, module.gitops]

  cluster_domain = var.cluster_domain
  cluster_vip    = var.cluster_vip
  ingress_pool   = "10.0.3.2"
}