apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      # Use NodePort to expose on node interfaces (now that Cilium kube-proxy replacement is enabled)
      hostNetwork: false
      hostPort:
        enabled: false
      
      # Use Deployment instead of DaemonSet
      kind: Deployment
      
      # Run on worker nodes only
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      
      # Service configuration - NodePort with fixed ports
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      
      # Ingress class configuration
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      
      # Enable metrics for monitoring
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false  # Enable later when we have Prometheus
      
      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      
      # Pod disruption budget
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      
      # Replica count for HA
      replicaCount: 2