apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      # Use hostNetwork to expose directly on Tailscale interface (like k3s)
      hostNetwork: true
      hostPort:
        enabled: false
        
      # Use DaemonSet to run on control-plane nodes
      kind: DaemonSet
      
      # Run on control-plane nodes (they have Tailscale connectivity)
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
        
      # Allow scheduling on control-plane nodes
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      
      # Service configuration - ClusterIP when using hostNetwork
      service:
        type: ClusterIP
      
      # Ingress class configuration
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      
      # Enable metrics for monitoring
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false  # Enable later when we have Prometheus
      
      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      
      # Configure health checks for hostNetwork mode
      livenessProbe:
        httpGet:
          path: /healthz
          port: 10254
          host: localhost  # Use localhost instead of pod IP for hostNetwork
        initialDelaySeconds: 10
        periodSeconds: 10
      
      readinessProbe:
        httpGet:
          path: /healthz
          port: 10254  
          host: localhost  # Use localhost instead of pod IP for hostNetwork
        initialDelaySeconds: 10
        periodSeconds: 1
      
      # Pod disruption budget for HA
      podDisruptionBudget:
        enabled: true
        minAvailable: 1