apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      # Use NodePort to expose on node interfaces (now that Cilium kube-proxy replacement is enabled)
      hostNetwork: false
      hostPort:
        enabled: false
        
      # Use Deployment instead of DaemonSet for NodePort
      kind: Deployment
      
      # Run on worker nodes (they also have Tailscale connectivity)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        # Spread pods across different nodes for HA
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: ingress-nginx
                  app.kubernetes.io/component: controller
              topologyKey: kubernetes.io/hostname
      
      # Service configuration - NodePort with different ports  
      service:
        type: NodePort
        nodePorts:
          http: 30081
          https: 30444
      
      # Ingress class configuration
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      
      # Enable metrics for monitoring
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false  # Enable later when we have Prometheus
      
      # Resource limits
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      
      # HA replicas on worker nodes
      replicaCount: 2
      
      # Pod disruption budget for HA
      podDisruptionBudget:
        enabled: true
        minAvailable: 1